config/routes.rb
Rails.application.routes.draw do

  resources :users
  
  resources :posts

  resources :replies

  resources :postcontents
  
  resources :subscriptions

  resources :zims

  get 'myzims/:id',to: 'myzims#index', as: 'myzim'

  get 'admin' => 'admin#index'
  
  get 'search' => 'search#index'
  
  get 'search/result'
  
  post 'search' => 'search#create'
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  root "sessions#new", as: 'zimcher'
  

end

app/models/zim.rb
class Zim < ActiveRecord::Base
  has_many :subscriptions
  has_many :posts, dependent: :destroy
  
  before_destroy :ensure_not_referenced_by_any_subscription
  
  private
  
  def ensure_not_referenced_by_any_subscription
    if subscriptions.empty?
      return true
    else
      errors.add(:base,'Subscription present')
      return false
    end
  end
end

app/controllers/zims_controller.rb
class ZimsController < ApplicationController
  include CurrentUser
  #before_action :set_user, only: [:index,:create]
  before_action :set_zim, only: [:show, :edit, :update, :destroy]

  # GET /zims
  # GET /zims.json
  def index
    @zims = Zim.all
  end

  # GET /zims/1
  # GET /zims/1.json
  def show
    @response = {
      :name => @zim.name,
      :description => @zim.description,
      :image_url => @zim.image_url,
      :publicity => @zim.publicity,
      :num_members => @zim.subscriptions.count,
      :num_posts => @zim.posts.count,
      :posts => @zim.posts  
    }
    
    respond_to do |format|
      format.html {render action: 'show'}
      format.json {render json: @response,status: :ok}
    end
    
  end

  # GET /zims/new
  def new
    @zim = Zim.new
  end

  # GET /zims/1/edit
  def edit
  end

  # POST /zims
  # POST /zims.json
  def create
    
    @zim = Zim.new
   
    @zim.name = zim_params[:name]
    @zim.description = zim_params[:description]

    respond_to do |format|
      if @zim.save
      
        if zim_params[:picture]
          uploaded_io = zim_params[:picture]
          s3 = Aws::S3::Resource.new(
            credentials: Aws::Credentials.new('AKIAJAE7VUWCVE6MJZTA ', 'IKIwmRHirTwvre4OacyNJgNXntSv3tKZSNxxSeTZ'),
            region: 'us-west-2')
            
          obj = s3.bucket('zimcher').object("zimssimages/#{@zim.id}")
          obj.put(body: uploaded_io)
          @zim.image_url = obj.public_url
          @zim.save
        end
        
        format.html { redirect_to myzim_path(id: User.find(session[:user_id])), notice: 'Zim was successfully created.' }
        format.json { render json: @zim, status: :created}
      else
        format.html { render :new }
        format.json { render json: @zim.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zims/1
  # PATCH/PUT /zims/1.json
  def update
  
    if zim_params[:picture]
      uploaded_io = zim_params[:picture]
      s3 = Aws::S3::Resource.new(
        credentials: Aws::Credentials.new('AKIAJAE7VUWCVE6MJZTA ', 'IKIwmRHirTwvre4OacyNJgNXntSv3tKZSNxxSeTZ'),
        region: 'us-west-2')
            
      obj = s3.bucket('zimcher').object("zimsimages/#{@zim.id}")
      obj.put(body: uploaded_io)
      @zim.image_url = obj.public_url
    end
    
    @zim.name = zim_params[:name]
    @zim.description = zim_params[:description]
    
    respond_to do |format|
      if @zim.save
        format.html { redirect_to @zim, notice: 'Zim was successfully updated.' }
        format.json { render json: @zim, status: :ok}
      else
        format.html { render :edit }
        format.json { render json: @zim.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zims/1
  # DELETE /zims/1.json
  def destroy
    @zim.destroy
    respond_to do |format|
      format.html { redirect_to zims_url, notice: 'Zim was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zim
      @zim = Zim.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zim_params
      params.require(:zim).permit(:name, :description, :picture)
    end
end

app/helpers/zims_helper.rb
module ZimsHelper
end

app/views/zims/_form.html.erb
<%= form_for(@zim) do |f| %>
  <% if @zim.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@zim.errors.count, "error") %> prohibited this zim from being saved:</h2>

      <ul>
      <% @zim.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/zims/copy of index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Zims</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Image url</th>
      <th>Publicity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @zims.each do |zim| %>
      <tr>
        <td><%= zim.name %></td>
        <td><%= zim.description %></td>
        <td><%= zim.image_url %></td>
        <td><%= zim.publicity %></td>
        <td><%= link_to 'Show', zim %></td>
        <td><%= link_to 'Edit', edit_zim_path(zim) %></td>
        <td><%= link_to 'Destroy', zim, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Zim', new_zim_path %>

app/views/zims/edit.html.erb
<h1>Editing Zim</h1>

<%= render 'form' %>

<%= link_to 'Show', @zim %> |
<%= link_to 'Back', zims_path %>

app/views/zims/index.html.erb
<p id="notice"><%= notice %></p>  
<h1>Listing Zims</h1>


<table class="table table-hover">
<% @zims.each do |zim| %>
  <tr>
    <td>
      <%= image_tag(zim.image_url, class: 'list_image') %>
    </td>
    <td>
      <dl>
        <dt><%= zim.name %></dt>
        <dd><%= truncate(strip_tags(zim.description), length: 80) %></dd>
      </dl>
    </td>
    <td>
      <%= link_to 'Show', zim %><br/>
      <%= button_to 'Subscirbe', subscriptions_path(zim_id: zim.id) ,class: "btn btn-info btn-sm"%><br/>
    </td>
  </tr>
<% end %>
</table>

app/views/zims/new.html.erb
<h1>New Zim</h1>

<%= render 'form' %>

<%= link_to 'Back', zims_path %>

app/views/zims/show.html.erb
<table>
  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
    <td>
      <%= image_tag(@response[:image_url], class: 'list_image') %>
    </td>
    <td class="list_description">
      <dl>
        <dt><%= @response[:name] %></dt>
        <dd><%= @response[:num_members] %>Members <%= @response[:num_posts] %>Posts <%= @response[:publicity]%>
        <dd><%= truncate(strip_tags(@response[:description]), length: 80) %></dd>
      </dl>
    </td>
  </tr>
</table>