config/routes.rb
Rails.application.routes.draw do

  resources :users
  
  resources :posts

  resources :replies

  resources :postcontents
  
  resources :subscriptions

  resources :zims

  get 'myzims/:id',to: 'myzims#index', as: 'myzim'

  get 'admin' => 'admin#index'
  
  get 'search' => 'search#index'
  
  get 'search/result'
  
  post 'search' => 'search#create'
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  root "sessions#new", as: 'zimcher'
  

end

app/controllers/myzims_controller.rb
class MyzimsController < ApplicationController
  before_action :set_user, only: [:index]

  def index
     
    subscriptions = @user.subscriptions
    
    @zims = Array.new() 
    
    subscriptions.each do |subscription|
      @zims.push(subscription.zim)
    end
    
    respond_to do |format|
      format.html {render action: 'index'}
      format.json {render json: @zims,status: :ok}
    end
  end
  
  private 
    def set_user
      @user = User.find(params[:id])
    end   
end

app/helpers/myzims_helper.rb
module MyzimsHelper
end

app/views/myzims/index.html.erb
Welcome <%=@user.name %> <%=button_to 'Logout', logout_path, method: :delete ,class: "btn btn-primary"%>

<table class="table">
<% @zims.each do |zim| %>
  <tr>
    <td>
      <%= image_tag(zim.image_url, class: 'list_image') %>
    </td>
    <td class="list_description">
      <dl>
        <dt><%= zim.name %></dt>
        <dd><%= truncate(strip_tags(zim.description), length: 80) %></dd>
      </dl>
    </td>
    <td class = "list_actions">
      <%= link_to 'Show', zim %><br>
      <%= link_to 'Unsubscirbe',zim%>
    </td>
  </tr>
<% end %>
</table>
<br />
<%= link_to 'Create a new Zim', new_zim_path %><br/>
<%= link_to 'Search',zims_path %><br>
<%= link_to 'My Profile',@user%>